# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1335347662);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1335347782);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1334639368);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1335423547);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 481280);
user_pref("browser.download.lastDir", "/home/anjana/Desktop");
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20120310011224");
user_pref("browser.startup.homepage_override.mstone", "rv:11.0");
user_pref("browser.syncPromoViewsLeft", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "langpack-en-ZA@firefox.mozilla.org:11.0,globalmenu@ubuntu.com:2.0.3,langpack-en-GB@firefox.mozilla.org:11.0,ubufox@ubuntu.com:0.9.4,{972ce4c6-7e08-4474-a285-3208198ce6fd}:11.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1335230323000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-11.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1335230258000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-11.0/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1331354689000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-11.0/extensions/globalmenu@ubuntu.com\",\"mtime\":1335230257000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-11.0/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1331354688000}}}]");
user_pref("extensions.lastAppVersion", "11.0");
user_pref("extensions.lastPlatformVersion", "11.0");
user_pref("extensions.pendingOperations", false);
user_pref("gfx.blacklist.direct2d", 4);
user_pref("gfx.blacklist.layers.direct3d10", 4);
user_pref("gfx.blacklist.layers.direct3d10-1", 4);
user_pref("gfx.blacklist.layers.direct3d9", 4);
user_pref("gfx.blacklist.layers.opengl", 3);
user_pref("gfx.blacklist.suggested-driver-version", "<Anything with EXT_texture_from_pixmap support>");
user_pref("gfx.blacklist.webgl.angle", 4);
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("gfx.blacklist.webgl.opengl", 4);
user_pref("idle.lastDailyNotification", 1335327790);
user_pref("intl.charsetmenu.browser.cache", "us-ascii, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1335204678);
user_pref("places.history.expiration.transient_current_max_pages", 79076);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_viewing_mixed", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1335204678);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1337692370);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
