#!/usr/bin/env bash

if [[ -s "/home/anjana/.rvm/environments/ruby-1.9.2-p318" ]]
then
  source "/home/anjana/.rvm/environments/ruby-1.9.2-p318"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/anjana/.rvm/environments/ruby-1.9.2-p318'" >&2
  exit 1
fi
  