#!/usr/bin/env bash

if [[ -s "/home/anjana/.rvm/environments/ruby-1.9.2-p320@rails3011" ]]
then
  source "/home/anjana/.rvm/environments/ruby-1.9.2-p320@rails3011"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/anjana/.rvm/environments/ruby-1.9.2-p320@rails3011'" >&2
  exit 1
fi
  